version: "3.7"

services:
  traefik:
    image: "traefik:v2.3"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    build: .
    image: jasonraimondi/scratchy:dev
    ports:
      - 3001:3001
    env_file:
      - .env.docker
    depends_on:
      - pg
      - mailhog
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`scratchy.localdomain`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3001"

  worker:
    image: jasonraimondi/scratchy:dev
    command:
      - node
      - /app/dist/worker.js
    env_file:
      - .env.docker
    depends_on:
      - pg
      - mailhog
      - redis

  seed-init:
    image: jasonraimondi/scratchy:dev
    command:
      - npm
      - run
      - seed
    env_file:
      - .env.docker
    depends_on:
      - pg
      - mailhog
      - redis
