version: "3.7"

services:
  api:
    build: .
    image: jasonraimondi/scratchy:dev
    environment:
      DOMAIN: localhost
      ACCESS_TOKEN_SECRET: 6fbf61ea-5214-40d8-a08b-4846daf8280an
      REFRESH_TOKEN_SECRET: de92ec07-29fe-457b-b71c-3aaf88ce01cbn
      ENABLE_DEBUGGING: 1
      MAILER: smtp://mailhog:1025
      TYPEORM_SYNCHRONIZE: 1
      TYPEORM_LOGGING: 1
      TYPEORM_ENTITIES: src/entity/**/*_entity.js
      TYPEORM_URL: postgres://scratchy:secret@pg:5432/scratchy
      TYPEORM_CONNECTION: postgres
#      CORS_URLS: "http://localhost"
    depends_on:
      - pg
      - mailhog
      - redis