version: "3.7"

services:
  pg:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: scratchy
      POSTGRES_USER: scratchy
      POSTGRES_PASSWORD: secret
    ports:
      - 30532:5432
    volumes:
      - pgdata1:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  pgdata1:
