version: "3.7"

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

  web:
    build: web/
    image: jasonraimondi/scratchy-web:dev
    ports:
      - 3000:3000
    depends_on:
      - pg
      - mailhog
      - redis

  api:
    build: api/
    image: jasonraimondi/scratchy-api:dev
    ports:
      - 3001:3001
    environment:
      NODE_ENV: "production"
      JWT_SECRET: "jUcizxqjvqPh2d3$bQp#Sy!3ScBiuNO2LC1"
      SALT: "qw^f6bq@iu%ga4kdjbewwen2@fsd"
      ENABLE_DEBUGGING: "true"
      URL: "https://scratchy.localdomain"
      API_URL: "https://scratchy.localdomain/api"
      DATABASE_URL: "postgres://scratchy:secret@pg:5432/scratchy"
      MAILER_URL: "smtp://mailhog:1025"
      QUEUE_URL: "redis://redis:6379/0"
      OAUTH_GOOGLE_ID: ""
      OAUTH_GOOGLE_SECRET: ""
      OAUTH_GITHUB_ID: ""
      OAUTH_GITHUB_SECRET: ""
    depends_on:
      - pg
      - mailhog
      - redis

  worker:
    image: jasonraimondi/scratchy:dev
    command:
      - node
      - /app/dist/worker.js
    depends_on:
      - pg
      - mailhog
      - redis

  seed-init:
    image: jasonraimondi/scratchy:dev
    command:
      - npm
      - run
      - seed
    depends_on:
      - pg
      - mailhog
      - redis

volumes:
  caddy-data:
  caddy-config: