name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "${{ matrix.os }} | Node ${{ matrix.node }}"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: bump to npm@7.x
        run: npm install -g npm
      - name: install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/api
      - name: run api unit tests
        run: npm run test:cov --ci --maxWorkers=2
        working-directory: packages/api
        env:
          CI: true
          URL: http://localhost
          JWT_SECRET: testing-access-token-secret
          OAUTH_GOOGLE_ID: abcdefg
          OAUTH_GOOGLE_SECRET: abcdefg
          OAUTH_GITHUB_ID: abcdefg
          OAUTH_GITHUB_SECRET: abcdefg
      - name: run api build
        run: npm run build --if-present
        working-directory: packages/api
      - name: report coverage to code climate
        working-directory: packages/api
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
